### ISSUE TITLE
Request GitHub deletes cached views of this repository

### ISSUE THREAD

**Issue by bburky** [cirosantilli/all-github-commit-emails#3]
Please [contact GitHub support](https://github.com/contact) and request that they delete any cached views accessible directly by SHA-1 hashes. Even though you have force pushed, this data is still accessible directly at: https://github.com/cirosantilli/all-github-commit-emails/tree/c92521051cdbdcbd9f137562d54564825ffae71d/emails

GitHub's behavior here is documented in the big red warning box at: https://help.github.com/articles/remove-sensitive-data/

/cc @arfon

**Comment by cirosantilli** [comment]
I already did as mentioned on the readme:

> and then you tell the engineering team to do a git gc to remove old commits from your APIs

**Comment by bburky** [comment]
I think you need to use the support form I linked and just request "please remove all cached views of the repository cirosantilli/all-github-commit-emails". It isn't something that happens automatically. Support responded very quickly when I did it once.

**Comment by cirosantilli** [comment]
https://github.com/cirosantilli/all-github-commit-emails/commit/f37574b1146cb20d1fadd73830b7bf22da285151
