### ISSUE TITLE
Have they ever made the blog post?

### ISSUE THREAD

**Issue by tomm1996** [cirosantilli/all-github-commit-emails#4]
>I’ll expect a future blog post on the matter from GitHub when you’ve got things sorted out, clarifying / quoting your data scraping policy, and saying that GitHub Archive and GHTorrent were not compliant. Will you forbid mass scrapping entirely, or just remove the emails? Will you modify the current events API as well?

**Comment by cirosantilli** [comment]
GitHub people are cool. But just not *that* cool. They just sneaked it into a privacy statement update: https://github.com/cirosantilli/all-github-commit-emails/tree/89a30078de7aff52819926294ae45869ac81383e#update-2016-08-30 which basically prevents you from publicly sharing the information.

So big corporations/secret services can scrape it, but this can't be shared. More power concentration.

Not sure how the privacy statement looks like now.
